### ISSUE TITLE
Can't load library from dropbox (iOS)

### ISSUE THREAD

**Issue by olibclarke** [HappenApps/Quiver#1328]
In the last several months, I have not been able to use the ios app. When I try to load my quiver library from Dropbox, it just isn't present in the list of files, even though I can see it on my dropbox folder on my mac (and it syncs correctly between two macs). Any ideas to address would be great! Deleting the dropbox account from Quiver and re-adding does not fix the issue. Deleting and re-installing the app also doesn't fix it.

**Comment by oscargong** [comment]
same here (iPad 12.9 inch 3rd gen, iOS 12)

**Comment by ylian** [comment]
Almost there with rewriting the iOS version in Swift. I will make sure this is addressed in the update.

**Comment by olibclarke** [comment]
That's exciting! Any chance of editing support? Inserting photos from camera roll? This would be fantastic!!

**Comment by kayoubi** [comment]
Any chance to support other cloud services? OneDrive / iCloud... right now the only options Dropbox or WebDAV 
Thanks

**Comment by partnerd55** [comment]
It's November 2021 and I still have this issue. Is it supposed to have been fixed by now?
