### ISSUE TITLE
Notes are disappearing on MacOS Catalina

### ISSUE THREAD

**Issue by ashleykleynhans** [HappenApps/Quiver#1386]
The content of my notes get lost whenever I move off the note since I upgraded to MacOS Catalina.

I was syncing my Library to Google Drive, but tried Dropbox and One Drive as well and still have the same issue.

**Comment by ylian** [comment]
Could you clarify what's happening? Did you mean that when you switch notes, the previous note is wiped out? Or your changes are not saved? A screenshot would help, thanks.

**Comment by ashleykleynhans** [comment]
Yes, when I switch notes, the content of the previous note is wiped out.

![image](https://user-images.githubusercontent.com/886709/68038744-4a846380-fcd3-11e9-83da-a13f07204248.png)
![image](https://user-images.githubusercontent.com/886709/68038763-51ab7180-fcd3-11e9-9585-6d762f1f69b3.png)
![image](https://user-images.githubusercontent.com/886709/68038773-55d78f00-fcd3-11e9-8c67-ae16c321a896.png)
![image](https://user-images.githubusercontent.com/886709/68038781-5a03ac80-fcd3-11e9-92c7-efd85282ced3.png)

**Comment by ylian** [comment]
It looks like a file permission issue. Somehow you couldn't write to the Quiver library file. 

Find your Quiver library file (File Menu > Show Library in Finder). Close Quiver. Double click on the Quiver library file to open Quiver again. This should fix the file permission issue.

**Comment by ashleykleynhans** [comment]
I tried that and still experiencing the same problem.

**Comment by ashleykleynhans** [comment]
It's not a file permission issue, because its saving the headings, but it's losing the content.

**Comment by ashleykleynhans** [comment]
Tried to move the Quiver library to my local Documents folder without cloud storage and the issue still persists.

**Comment by ylian** [comment]
Could you check the json file and see if the content is saved? That will help narrow down the issue.

You can right click on the note, "Show in Finder", then open the .qvnote file in a text editor. There should be a "meta.json" file and a "content.json" file. "content.json" should contain the note content.

**Comment by ashleykleynhans** [comment]
Nope, those files are missing.

**Comment by ylian** [comment]
So you can see the .qvnote file, but it doesn't contain any files inside? (Right click on .qvnote file and "Show Package Contents")

**Comment by ashleykleynhans** [comment]
Yes I can see .qvnote but the contents are missing.

**Comment by ashleykleynhans** [comment]
Working note

`[18:52:25] [LP] [~/Documents/Quiver.qvlibrary/03CE43AA-5B44-424D-A9A7-D4BB17DC88F5.qvnotebook/15559C8C-96B9-48F7-AC5B-16FB210E37D4.qvnote] $ ls -la
total 24
drwxr-xr-x   4 ashley  staff   128 Jun 25 11:04 .
drwxr-xr-x  26 ashley  staff   832 Jun 25 12:42 ..
-rw-------@  1 ashley  staff  4511 Feb  3  2017 content.json
-rw-------@  1 ashley  staff   157 Feb  3  2017 meta.json`

Missing note

`[18:54:52] [LP] [~/Documents/Quiver.qvlibrary/2E02AD08-9D5C-4621-97E5-62EFE753C097.qvnotebook/0D4C93E3-EB73-44FB-A10D-C6BF5A83FB4B.qvnote] $ ls -la
total 0
drwxr-xr-x@ 2 ashley  staff   64 Nov  1 18:48 .
drwxr-xr-x@ 4 ashley  staff  128 Nov  1 18:48 ..`

**Comment by ylian** [comment]
I see. So there are two possibilities.

1. Still a file permission issue. The note title is also saved to a cache db, and that's why you can still see it.
2. An issue with cache db.

I suggest to try resetting the cache.
1. Remove these two files:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
2. Double click on your Quiver library file to reopen.

**Comment by ashleykleynhans** [comment]
Tried that with the app open and then again with the app closed, and still having the same issue.

**Comment by ylian** [comment]
Then it can only be a file permission issue. If you open Console.app and filter by name "Quiver", you might see some error logs like "couldn't write file". The error logs might provide more clues why the files couldn't be written to.

**Comment by ashleykleynhans** [comment]
Latest Catalina update seems to have fixed this issue.

**Comment by ylian** [comment]
@ashleykleynhans Thanks for letting me know!

**Comment by minhnguyen2013** [comment]
I have the same issue and my notes are lost

**Comment by ylian** [comment]
@minhnguyen2013 Please email the details to me (ylian@happenapps.com) and I will help you from there.
