### ISSUE TITLE
Body text of all note disappeared

### ISSUE THREAD

**Issue by sdr0x07b6** [HappenApps/Quiver#1395]
- Quiver.app v3.2.6, v.3.2.7
- macOS 10.14.6

## Problem

The body text of all notes suddenly disappeared.
Only the subject of the note is displayed.

I was worried that data had disappeared, but text is in JSON.
`Quiver.qvlibrary/*.Qvnotebook/*.Qvnote/content.json`

In search of Quiver, it will also hit information in the body text.
However, if you touch body text of a note that does not display body text, it will be saved empty and body text data will disappear.

## I tried to solve

- Moved library
- Imported after library copied
- Reinstalled Quiver.app

## Question

I couldn't solve it anyway.
Do you have any tips for the problem with body text disappearing?
Also, please tell me path of Quiver preference file.

**Comment by ylian** [comment]
This indicates that Quiver can't read the note files for some reason. It's even more strange that it looks that it can write to the file.

I suggest trying a few things:
1. Reset the app preference (Preferences > Advanced > Restore Defaults) then reopen Quiver.
(fyi, Quiver's preference file is here: ~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/settings.json)
2. If your Quiver library is on Dropbox, open the Dropbox app. A few users reported similar issues that were fixed by opening the Dropbox app.
3. If the problem persists, maybe do a clean install:
   1. Take note of your library's location (Preferences > Sync > Library Location). Make a copy of your library file for backup.
   2. Completely remove ~/Library/Containers/com.happenapps.Quiver
   3. Reopen Quiver and then select your library to open (File Menu > Open Library).

**Comment by sdr0x07b6** [comment]
Thank you for your quickly response!
The logic of the cause is not well understood, however has been resolved anyway!

Certainly I was using Dropbox.
It was not solved only by starting Dropbox, but it was solved by restarting the system and starting Dropbox repeatedly.

If it reproduces again, next time I want to try deleting the preference file.

Thank you.
