### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by jarandaf** [HappenApps/Quiver#23]
What's the expected way of searching by tag? I am trying to find some notes by typing #{someTag} but although there are some notes tagged with {someTag}, no notes are found.

**Comment by ylian** [comment]
#tag

**Comment by jarandaf** [comment]
Well, I meant {someTag} is actually a string value representing a tag. Using # followed by the tag string value does not seem to work (no notes are found although there are notes tagged with such tag).

**Comment by ylian** [comment]
It should work. I wonder if your index file is corrupted. Created a note, put in some words, and try to search for those.

**Comment by jarandaf** [comment]
Search by text/title works fine.

**Comment by ylian** [comment]
Does it work fine if you create a new note? I fixed a bug yesterday that can corrupt the search index file, and new notes won't be indexed.

**Comment by jarandaf** [comment]
I provide an example:

![tags](https://cloud.githubusercontent.com/assets/2277398/5919300/dbd863c4-a632-11e4-96b7-35ed6b82d63b.png)

Searching by #statistics does not work. I am not sure whether tags including spaces (e.g. "machine learning") should be accepted or how they should behave.

Adding new notes and tagging them does not solve the issue (I purchased the app some days ago and I don't see any update on mac store so I understand I can't verify your bug fix).

**Comment by ylian** [comment]
Is it possible to send me your Quiver library? support@happenapps.com

Yes the fix is not out yet. I am finishing things up.

**Comment by ylian** [comment]
Just for other users who might read this thread, it turns out to be two minor issues:

1. You need to hit enter after #tag to search. This is inconsistent with the behavior when searching for words.
2. There is no way to search for tag names with spaces in them, such as "machine learning".

I will keep this ticket open until I fix these two issues.

**Comment by ylian** [comment]
For users who might read this thread in the future, it turns out to be two minor issues:

1. Tag search only matches exact tag names. Partial tag matching is not supported.
2. There is no way to search for tags with spaces in them, such as "machine learning".

I have to think about what's the expected behavior for the first one. But the second one should definitely be fixed. Keep this ticket open until both issues are addressed.

**Comment by romainhild** [comment]
I had the same issue the first time I installed the app, and after a reinstall it works now. 
But I reinstalled the whole system (10.9) in the same process.

**Comment by robdecker** [comment]
:+1: for partial tag name searching

**Comment by JMichaelTX** [comment]
> Tag search only matches exact tag names. Partial tag matching is not supported.

@ylian , please add support for partial tag matching.  This is hugely powerful, and I use it all the time in Evernote.

For example I have two related tags:
SW.JS.JavaScript
SW.JS.JXA

Sometimes I need to search for anything JavaScript related, so, in Evernote I would use:
`SW.JS.*`

I have a lot of tags with this type of hierarchy built into the name.  It makes it very easy to search for all notes with tags at a certain level.

Thanks.
