### ISSUE TITLE
Latest 3.0.6 version shows incorrect image size and resolution in Text Cell option.

### ISSUE THREAD

**Issue by jenhsun** [HappenApps/Quiver#849]
I would like to report an image resizing issue on latest 3.0.6. My mac version is latest Sierra 10.12.4
When I import image to "Text cell" option, image size and resolution is incorrect. I figure that I have to select "Markdown cell" then back to "Text cell" for correcting the image.

**Comment by ylian** [comment]
Could you send me the image for testing? Thanks. Please zip it and send to ylian@happenapps.com, instead of pasting it here (GitHub might resize the image).

**Comment by ylian** [comment]
Thanks for sending me the image.

It's a bug and I will fix it in the next update. In the meantime, here is a workaround: in Preferences > Styles > Editor, add the following:

```css
img {
  height: auto;
}
```

**Comment by jenhsun** [comment]
Yap, I test your add on and Problem solved. Thanks.

**Comment by ylian** [comment]
Let's leave this open until I apply this fix permanently in the next update.

**Comment by jenhsun** [comment]
Hi, Lian
I would like to report to you that your above solution can't fix image size problem. Today I try to delete the original image, delete Note, and add a new one. The problem still re-surface. Now my only solution is still my original one - After clicking the "image icon" for importing, I have to switch to "Markdown Cell" mode, then switch back to "Text Cell" mode. This way can refresh image and show correct size to fit the cell block.

**Comment by ylian** [comment]
You would have to add this to preview as well.

**Comment by jenhsun** [comment]
@ylian I used to be a software developer and I did test the way you mention above. My guess the problem is app's cache refresh. Either after importing app didn't refresh Text cell, or because you did improve Markdown cell but something happened to Text cell. So I have to switch to Markdown mode and then switch back to Text mode for image correction.

**Comment by jenhsun** [comment]
One more thing, you can try to add one new note, then: 
1. select to markdown mode.   
2. import image.   
3. select to text mode   

and see what image will happen next. 
You better play around all those cell options steps by steps. The relationship between each cell might rise new problems if you can watch it closely.

**Comment by ylian** [comment]
Just tried:
1. Add a new note.
2. Switch to the Markdown cell
3. Import image using the image icon in the toolbar
4. Switch to text node

The image is fine for me:

![image](https://cloud.githubusercontent.com/assets/984895/25430970/f46e29be-2a7e-11e7-9cf2-b1a0a113bab0.png)

This is with the above css fix applied:

![image](https://cloud.githubusercontent.com/assets/984895/25430993/07b1c7ce-2a7f-11e7-8144-be8a3c5631b6.png)

**Comment by jenhsun** [comment]
@ylian I see. You put `img { height: auto; }` in front of the rest of code. Mine is put in the end of code. My guess it might be the problem. Let me try that again.

**Comment by jenhsun** [comment]
@ylian No, It still can't work after I carefully follow what you mention above. Let me show them below.  

Steps as follow as yours:
### Markdown Cell mode:
![Imgur](http://i.imgur.com/yKaKIJX.jpg)    

### Then Switch Back to Text Cell mode:    
![Imgur](http://i.imgur.com/lHxMwcB.jpg)

**Comment by ylian** [comment]
I see. It could be overwritten by other CSS setting. It might even be overwritten by certain themes. 

In that case, try this:

img {
   height: auto !important;
}

**Comment by ylian** [comment]
I see what the problem is. It's a different problem. The image size is non-integer. The Markdown parser fails to render because of that. 

Please attach this image so I can fix. Thanks!

**Comment by ylian** [comment]
Actually no need to attach the image if it's sensitive. I will fix the non-integer size issue. Appreciate your help!

**Comment by ylian** [comment]
Both issues (image scale, non-integer image size) are fixed in 3.0.7.

**Comment by jenhsun** [comment]
@ylian I would like to thank you for this fix. A thumb up to you. However, there is a problem not related to Quiver but is still affected.   

Because Quiver can't display/addon PDF file. I have to use MacOS's preview or Acrobat converting pdf to jpg. And the result of JPG still can't proper display on Quiver 3.0.7. So I have to use other image tool (ex. Monosnap) convert jpg to jpg again. After importing back to Quiver, it will display correctly on Quiver 3.0.7. 

Hopefully, Quiver could have PDF importing feature in the future. So I won't need to convert to jpg images. Thanks.

**Comment by ylian** [comment]
@jenhsun Inline PDF support will be implemented sometime down the road.
